### ISSUE TITLE
Puzzles of hamming distance

### ISSUE THREAD

**Issue by lightningtyb** [studio-ousia/bpr#6]
Hi, this work is awesome for efficient retrieval. And I learned a lot from this. I have a puzzle about the hamming distance between query hash code and doc hash code. In the paper, it is stated that hamming distance(q,d) = 1/2 (const - inner product<q,d>). And in the source code of index.py, the score is calculated by np.einsum("ijk,ik->ij", passage_embeddings, query_embeddings). I wonder the source code is consistent with the equation. And I'm not sure the shape of passage_embeddings and query_embeddings. Hope your reply. Thank u so much!

**Comment by ikuyamada** [comment]
Hi @lightningtyb,
Thanks for your interest in our work!
`np.einsum("ijk,ik->ij", passage_embeddings, query_embeddings)` is equivalent to `np.matmul(passage_embeddings, query_embeddings[:, :, None])[:, :, 0]`. It computes the inner product between query embeddings and passage embeddings. Please note that the `const` part can be ignored safely.

```python
>>> import numpy as np
>>> BATCH_SIZE = 4
>>> PASSAGE_SIZE = 20
>>> EMB_DIM = 100
>>> EMB_SIZE = 100
>>> query_embeddings = np.random.rand(BATCH_SIZE, EMB_SIZE)
>>> passage_embeddings = np.random.rand(BATCH_SIZE, PASSAGE_SIZE, EMB_SIZE)
>>> result1 = np.einsum('ijk,ik->ij', passage_embeddings, query_embeddings)
>>> result2 = np.matmul(passage_embeddings, query_embeddings[:, :, None])[:, :, 0]
>>> np.allclose(result1, result2)
True
```

**Comment by lightningtyb** [comment]
@ikuyamada Thanks for replying. That helps me a lot.

**Comment by ikuyamada** [comment]
Please reopen this issue if you have any further questions
